FROM couchbase:6.0.0

#COPY configure-node.sh /opt/couchbase

#RUN ["chmod", "+x", "/opt/couchbase/configure-node.sh"]

#HEALTHCHECK --interval=5s --timeout=3s CMD curl --fail http://localhost:8091/pools || exit 1

#CMD ["/opt/couchbase/configure-node.sh"]